language: go
go:
  - 1.x
os:
  - linux
before_install:
  - go get golang.org/x/lint/golint
  - go get honnef.co/go/tools/cmd/staticcheck
  - go get -d ./...
script:
  - go build -tags=gofuzz ./...
  - go vet ./...
  - staticcheck ./...
  - ./scripts/golint.sh
  - go test -v -race ./...
